### ISSUE TITLE
no file /root/rolltests/hadoop.t 

### ISSUE THREAD

**Issue by pnavaro** [sdsc/hadoop-roll#2]
Dear sdsc,
I followed instructions, everything seems going fine but at the end the /root/rolltests/hadoop.t 
file is not installed. 
I installed sdsc-roll and tests passed.
~~~
# rocks run roll hadoop | bash
Cleaning repos: Rocks-6.2
Cleaning up Everything
~~~
nothing else...

Pierre

**Comment by jjhayes** [comment]
Sorry for the delay in responding. Most of the SDSC rolls don't install on the front end; in order to do so, you need to ask Rocks for the installation script for a login or compute node. This command, run on the front end, should work with this and other rolls:

% rocks run roll gnutools host=NAME | bash

where NAME is a compute or login node dns name, e.g., "compute-0-0".

I've updated the README.md file to discuss this.

Jim

**Comment by pnavaro** [comment]
Thank you
